
title: Speaker profile
email: koshik.raj@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Collection of all the past talks and the future scheduled talks.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://koshikraj.com"

# Company Information
company_name: Consenso Labs
address_line: Bengaluru
telephone_number: +919900589280
fax_number:
company_email: admin@consensolabs.com
google_map: https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d3618.727010735933!2d91.837871!3d24.907291700000002!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2s!4v1404919738144

# Social Link
facebook_link: https://www.facebook.com/koshik.raj
twitter_link: https://www.twitter.com/rajkoshik
linkedin_link: https://www.linkedin.com/koshikraj
googleplus_link: https://plus.google.com/u/0/+koshikraj

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
